name: Auto Sync Fork

on:
  push:
    branches:
      - main # 또는 원본 레포지토리의 기본 브랜치 이름
  pull_request:
    types: [opened, reopened, synchronize] # PR생성, 머지, 닫힘

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 전체 히스토리 가져오기

      - name: Configure Git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Sync with upstream repository
        run: |
          git remote add upstream https://github.com/Part3-Team7-Taskify/part3-team7-taskify.git           
          git fetch upstream
          git merge upstream/${GITHUB_REF:11} # PR이 머지된 브랜치 병합
          git push origin main # 또는 개인 레포지토리의 기본 브랜치
        env:
          GITHUB_REF: ${{ github.ref }}
